### PR TITLE
Fix polar plugin

### LINKED ISSUE #450: Polar plugin uses hardcoded deviceId’s to establish the connection to the device
The polar plugin uses the specific api.connectToDevice(deviceId) function from the Polar SDK to automatically connect to the device of which the deviceId is hardcoded in the plugin.

This deviceId can be changed in PolarManager.

[This PR for Polar-autoscan ](https://github.com/RADAR-base/radar-commons-android/pull/451) does not use a hardcoded deviceId, but the api.autoConnectToDevice() function from the Polar SDK to automatically connect to a compatible Polar device. 
Although this might be the preferred method, this connection could not always be established for the ‘Polar Vantage V3’ and ‘Polar Sense’ devices.

A solution would be to either resolve the issues with the autoscan function, or to add a pop-up in the pRMT app in which the user can manually add the deviceId, to which a connection could be established (as in the current Polar plugin).

### PR DESCRIPTION
**Pull request by yatharthranjan**
- This fixes the auto-connect of polar devices
- Searches for polar devices every 5 seconds until one is found
- On connection to a new device, it stores the Polar device ID and always reconnects to it in the future. Only one ID is stored at once.
- Pair a new device using the "Reset Polar Device ID" action button.
- Tested with Polar Vantage V3
- Also fixes reconnection of the device and reload functionality in the plugin
- Closes #450, #453, #454

### CODE REVIEW

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt [hunk 1]
```diff
@@ -149,42 +149,92 @@ class PolarManager(
...
+        autoConnectToPolarSDK()
+    }
+
+    private fun autoConnectToPolarSDK() {
+        if (autoConnectDisposable != null && !autoConnectDisposable!!.isDisposed) {
+            autoConnectDisposable?.dispose()
+        }
+
+        autoConnectDisposable = Flowable.interval(0, 5, TimeUnit.SECONDS)
+            .observeOn(AndroidSchedulers.mainThread())
```
Comment (this-Aditya) [inline plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:203]: I am not very familiar with RxJava, we are using `observeOn(AndroidSchedulers.mainThread())` in every method. It seems that this forces the code inside these methods to always execute on the main thread, which could potentially freeze the UI

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt [hunk 2]
```diff
@@ -149,42 +149,92 @@ class PolarManager(
...
-                var batteryLevel = level.toFloat() / 100.0f
+                val batteryLevel = level.toFloat() / 100.0f
                 state.batteryLevel = batteryLevel
-                Log.d(TAG, "Battery level $level%, which is $batteryLevel at " + currentTime)
-                send(batteryLevelTopic, PolarBatteryLevel(name, currentTime, currentTime, batteryLevel))
+                logger.debug("Battery level $level%, which is $batteryLevel at $currentTime")
+                send(
+                    batteryLevelTopic,
+                    PolarBatteryLevel(name, currentTime, currentTime, batteryLevel)
+                )
```
Comment (this-Aditya) [inline plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:173]: Safehandler instance can be used to send data in background.

**Review by this-Aditya — COMMENTED** [review]
Hi @yatharthranjan, this PR looks good, but I have identified some areas for improvement in the code merged from PR #448 that could optimize the plugin for better performance and usability.

**Comment by yatharthranjan** [comment]
Hi @this-Aditya, thanks for the comments. I also recognised various issues with the existing polar impl. but only made changes in this PR to fix the auto-connect, as there are other issues in this repo for those things that can be handled in specific PRs (and also wanted to test this in isolation). However, I will incorporate your suggestions (and delegate to separate PR/issue where suitable). Thanks

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt (hunk 1 above)
Comment (yatharthranjan) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:203]: Yes, that is a good spot; I am also not very familiar with RxJava but this was provided in Polar documentation, hence being used here. I will try to remove it and test it. However, at least here it does not freeze the UI, as it only runs initially until the device is paired. Once there is a paired device, it will always connect to that and will not need scanning of devices. But I agree that sending the data could be an issue.

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarService.kt [hunk 3]
```diff
@@ -1,23 +1,19 @@
...
 /**
  * A service that manages the Polar manager and a TableDataHandler to send store the data of
  * the phone sensors and send it to a Kafka REST proxy.
  */
 class PolarService : SourceService<PolarState>() {
     private lateinit var handler: SafeHandler
-//    private lateinit var context: Context
+
     override val defaultState: PolarState
         get() = PolarState()
```
[the remark this answers is not in the document]
Comment (yatharthranjan) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarService.kt:18]: I have left it for now as it does set hasAcceleration to true, we can remove it in future if not required (I don't think it matters that much TBH)

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt [hunk 4]
```diff
@@ -122,20 +119,23 @@ class PolarManager(
...
                 status = SourceStatusListener.Status.CONNECTING // green dots
-                Log.d(TAG, "Device connecting ${polarDeviceInfo.deviceId}")
+                logger.debug("Device connecting ${polarDeviceInfo.deviceId}")
             }
 
             override fun deviceDisconnected(polarDeviceInfo: PolarDeviceInfo) {
-                Log.d(TAG, "Device disconnected ${polarDeviceInfo.deviceId}")
+                logger.debug("Device disconnected ${polarDeviceInfo.deviceId}")
                 isDeviceConnected = false
                 status = SourceStatusListener.Status.DISCONNECTED // red circle
```
[the remark this answers is not in the document]
Comment (yatharthranjan) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:129]: Yes this is something that needs to be worked on and tested. There are already issues related to it #453  and #454. I am going to leave this for separate PR in the future. But please feel free to add a new issue to track this.

**Comment by this-Aditya** [comment]
Oh, okay. I thought this was the finalized PR for the Polar plugin, which is why I mentioned these here 😅

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt (hunk 1 above)
Comment (this-Aditya) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:203]: Alternatively, we can use `observerOn` with the main thread and simply wrap the code inside the methods using a handler.

> However, at least in this case, it does not freeze the UI since it only runs initially until the device is paired.

Okay, but there are other functions as well that use `observeOn(AndroidSchedulers.mainThread())`.

**Review by this-Aditya — APPROVED** [review]
LGTM, thanks.

**Comment by yatharthranjan** [comment]
>Oh, okay. I thought this was the finalized PR for the Polar plugin, which is why I mentioned these here 😅

No worries at all, very valuable feedback. I have tried to incorporate it where possible and added some other changes. This now closes #450, #454, #453.

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt [hunk 5]
```diff
@@ -14,35 +13,39 @@ import com.polar.sdk.api.model.*
...
+        createCache("android_polar_ecg", PolarEcg())
+    private val heartRateTopic: DataCache<ObservationKey, PolarHeartRate> =
+        createCache("android_polar_heart_rate", PolarHeartRate())
+    private val ppIntervalTopic: DataCache<ObservationKey, PolarPpInterval> =
+        createCache("android_polar_pulse_to_pulse_interval", PolarPpInterval())
+    private val ppgTopic: DataCache<ObservationKey, PolarPpg> =
+        createCache("android_polar_ppg", PolarPpg())
 
     private val mHandler = SafeHandler.getInstance("Polar sensors", THREAD_PRIORITY_BACKGROUND)
     private var wakeLock: PowerManager.WakeLock? = null
```
[the remark this answers is not in the document]
Comment (yatharthranjan) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:44]: I have left it in for now as the app did loose connection with the device without this after a while of screen being off.

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt [hunk 6]
```diff
@@ -187,6 +186,33 @@ class PolarManager(
...
+        if (ppiDisposable != null && !ppiDisposable!!.isDisposed) {
+            ppiDisposable?.dispose()
+        }
+        if (ppgDisposable != null && !ppgDisposable!!.isDisposed) {
+            ppgDisposable?.dispose()
+        }
+
+        disconnectToPolarSDK(deviceId)
+        mHandler.stop {
+            wakeLock?.release()
```
Comment (this-Aditya) [inline plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:214]: Is it necessary to use a wake lock here, considering that this specific functionality is already provided by services?

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt [hunk 7]
```diff
@@ -125,8 +123,7 @@ class PolarManager(
             override fun deviceDisconnected(polarDeviceInfo: PolarDeviceInfo) {
                 logger.debug("Device disconnected ${polarDeviceInfo.deviceId}")
                 isDeviceConnected = false
-                status = SourceStatusListener.Status.DISCONNECTED // red circle
-
+                disconnect()
```
Comment (this-Aditya) [inline plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:126]: I am not entirely sure, but does it not loop between connecting and disconnecting the manager when this callback is received? If so, we could add logic specific to the needs of this plugin ( such as handling the merging of `::disconnect` with the `UNAVAILABLE` status or similar to this) to prevent the loop and starting from READY again during reconnections.

**Please disregard this review if the behavior is functioning correctly with `::disconnect` as well.**

**Review by this-Aditya — COMMENTED** [review]
Thanks @yatharthranjan  for updating this PR. It looks great so far. Could you please review these additional comments and include them if necessary?

Thanks

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt (hunk 5 above)
[the remark this answers is not in the document]
Comment (this-Aditya) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:44]: Okay, sorry I skipped it. I’ve recommented.

File: plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt (hunk 7 above)
Comment (yatharthranjan) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:126]: I don't think I completely understand; when the device is disconnected, this callback is called, which sets the plugin state to disconnect. The recording is started again, and it becomes ready, looking for the device to connect again.

Here are logs showing the process

```
2024-09-09 16:01:27.858 19539-19539 pRMT:PolarManager       org.radarcns.detail                  D  Device disconnected CF27042A
2024-09-09 16:01:27.859 19539-19539 pRMT:SourceServiceConn* org.radarcns.detail                  I  AppSource status changed of source Polar Vantage V3 CF27042A
2024-09-09 16:01:27.859 19539-19539 pRMT:SourceServiceConn* org.radarcns.detail                  I  Updated source status to DISCONNECTING
2024-09-09 16:01:27.859 19539-19539 pRMT:RadarService       org.radarcns.detail                  I  Source of ServiceConnection<org.radarbase.passive.polar.PolarService> was updated to DISCONNECTING
2024-09-09 16:01:27.874 19539-19539 pRMT:SourceServiceConn* org.radarcns.detail                  I  AppSource status changed of source null
2024-09-09 16:01:27.874 19539-19539 pRMT:SourceServiceConn* org.radarcns.detail                  I  Updated source status to DISCONNECTED
2024-09-09 16:01:27.874 19539-19539 pRMT:RadarService       org.radarcns.detail                  I  Source of ServiceConnection<org.radarbase.passive.polar.PolarService> was updated to DISCONNECTED
2024-09-09 16:01:27.875 19539-19665 pRMT:RadarService       org.radarcns.detail                  I  Starting recording on connection ServiceConnection<org.radarbase.passive.polar.PolarService>
2024-09-09 16:01:27.880 19539-11102 pRMT:SourceService      org.radarcns.detail                  I  Starting recording now for PolarService
2024-09-09 16:01:27.883 19539-11102 pRMT:PolarManager       org.radarcns.detail                  D  Connecting to Polar API
2024-09-09 16:01:27.883 19539-19539 pRMT:SourceServiceConn* org.radarcns.detail                  I  AppSource status changed of source Polar
2024-09-09 16:01:27.883 19539-19539 pRMT:SourceServiceConn* org.radarcns.detail                  I  Updated source status to READY
2024-09-09 16:01:27.884 19539-19539 pRMT:RadarService       org.radarcns.detail                  I  Source of ServiceConnection<org.radarbase.passive.polar.PolarService> was updated to READY

```

I did not notice any looping in my testing.

Comment (this-Aditya) [reply plugins/radar-android-polar/src/main/java/org/radarbase/passive/polar/PolarManager.kt:126]: Okay, that’s great. I have observed this looping behavior in other plugins, but I have not worked with any wearable devices for pRMT, so I was not sure about the behavior for wearables on `::disconnect`

Thanks for the logs.

**Review by this-Aditya — APPROVED** [review]

**Comment by afolarin** [comment]
Nice work 👍🏽 @this-Aditya @yatharthranjan briefed me on some of the caveats, but this will still definitely be very useful, particularly as we push for good gold standards for benchmarking studies.

**Comment by this-Aditya** [comment]
Thanks @afolarin, glad to hear it.
